activate pre on linux

diff --git a/ci/azure/linux.yml b/ci/azure/linux.yml
--- a/ci/azure/linux.yml
+++ b/ci/azure/linux.yml
@@ -39,9 +39,17 @@ jobs:
     condition: eq( variables['INSTALL_TYPE'], 'conda' )
   - script: |
       sudo chmod +x ci/azure/install.sh
-      ./ci/azure/install.sh
+      if [[ -z "${USE_PRE}" ]]; then
+        ./ci/azure/install.sh || echo -e "\043#vso[task.logissue type=warning;] Error during pre-package installation"
+      else
+        ./ci/azure/install.sh
+      fi
     displayName: 'Install dependencies'
   - script: |
       sudo chmod +x ci/azure/script.sh
-      ./ci/azure/script.sh
+      if [[ -z "${USE_PRE}" ]]; then
+        ./ci/azure/script.sh || echo -e "\043#vso[task.logissue type=warning;] Error during tests on PRE matrix"
+      else
+        ./ci/azure/script.sh
+      fi
     displayName: 'Install DIPY and Run Tests'
