export some viz env var for linux

diff --git a/.github/workflows/test_template.yml b/.github/workflows/test_template.yml
--- a/.github/workflows/test_template.yml
+++ b/.github/workflows/test_template.yml
@@ -98,14 +98,10 @@ jobs:
     - name: Setup Headless
       if: ${{ inputs.enable-viz-tests }}
       run: tools/ci/setup_headless.sh
-    # Enable tmate debugging of manually-triggered workflows if the input option was provided
-    - name: Setup tmate session
-      if: ${{ failure() }}
-      uses: mxschmitt/action-tmate@v3
     - name: Run the Tests
       run: |
         if [ "${{ inputs.use-pre }}" == "true" ]; then
-          tools/ci/run_tests.sh || echo "::warning::Job Experimental Job so failure ignored!"
+          tools/ci/run_tests.sh || echo "::warning::Experimental Job so failure ignored!"
         else
           tools/ci/run_tests.sh
         fi
