skip pre task if failure

diff --git a/.github/workflows/test_template.yml b/.github/workflows/test_template.yml
--- a/.github/workflows/test_template.yml
+++ b/.github/workflows/test_template.yml
@@ -93,15 +93,27 @@ jobs:
         channels: defaults, conda-forge
         use-only-tar-bz2: true
     - name: Install Dependencies
-      run: tools/ci/install_dependencies.sh
+      run: |
+        if [ "${{ inputs.use-pre }}" == "true" ]; then
+          tools/ci/install_dependencies.sh || echo "::warning::Experimental Job so Install Dependencies failure ignored!"
+        else
+          tools/ci/install_dependencies.sh
     - name: Install rtools (mingw-w64)
       if: runner.os == 'Windows'
       run: |
         choco install rtools -y --no-progress --force --version=4.0.0.20220206
         echo "/c/rtools40/ucrt64/bin;" >> $GITHUB_PATH
         echo "PKG_CONFIG_PATH=/c/opt/64/lib/pkgconfig;" >> $GITHUB_ENV
+    - name: Install OpenMP
+      if: runner.os == 'macOS'
+      run: |
+        brew install libomp
     - name: Install DIPY
-      run: tools/ci/install.sh
+      run: |
+        if [ "${{ inputs.use-pre }}" == "true" ]; then
+          tools/ci/install.sh || echo "::warning::Experimental Job so Install DIPY failure ignored!"
+        else
+          tools/ci/install.sh
     - name: Setup Headless
       if: ${{ inputs.enable-viz-tests }}
       run: tools/ci/setup_headless.sh
